doc: adding about.md
containerish/docs pull request #2
Opened 2021-09-14 14:55 UTC by guacamole

This file adds another page to our blog, About.md contains project vision and community proposal.

2021-09-14 16:16 UTC, jay-dee7 requested changes
@guacamole documentation.md is already being tracked by PR #1 can you please remove it from here?

2021-09-14 16:25 UTC, jay-dee7 commented
> @guacamole documentation.md is already being tracked by PR #1 can you please remove it from here?

NVM, changed it

2021-09-15 16:58 UTC, Sanyambansal76 commented on about.md
> +We are a small team of developers working towards decentralizing the container experience.
```suggestion
We are a small team of developers working towards decentralizing the container registry experience.
```

2021-09-15 17:04 UTC, Sanyambansal76 commented on about.md
> +We use Akash for compute which is a decentralized cloud provider offering their services for a very affordable price. Secondly we use Skynet as our storage layer which again is a part of Decentralize
I think we should keep Akash and Skynet separate points, and make the Akash and skynet the hyperlink to the their respective websites

2021-09-15 17:07 UTC, Sanyambansal76 commented on about.md
> +We are a small team of developers working towards decentralizing the container experience.
@guacamole @jay-dee7 I think it will be also good if we add something about the recent Akash hackathon which gave born to this project

2021-09-15 17:11 UTC, Sanyambansal76 commented on about.md
> +We use Akash for compute which is a decentralized cloud provider offering their services for a very affordable price. Secondly we use Skynet as our storage layer which again is a part of Decentralize
@guacamole if we split this paragraph into multiple bullet points then it will be more clear to user

2021-09-15 17:12 UTC, Sanyambansal76 reviewed
@jay-dee7 @guacamole see if comments make sense

2021-09-15 17:16 UTC, jay-dee7 commented on about.md
> +We are a small team of developers working towards decentralizing the container experience.
@Sanyambansal76 that we can add as an addition later on, this is just a simple intro to get going. We can add a blog post with the hackathon winning announcement and then update it here as a link

2021-09-15 17:54 UTC, Sanyambansal76 commented on about.md
> +We are a small team of developers working towards decentralizing the container experience.
Cool then

2021-09-19 09:21 UTC, jay-dee7 approved these changes
@guacamole LGTM, lets push this one to the blog site and see how it looks

2021-09-19 09:24 UTC, merged